import ChatHeader from "./components/chatheader/ChatHeader";
import InputBar from "./components/InputBar";
import Reply from "./components/Reply";
import Sidebar from "./components/sidebar/Sidebar";
import ChatContext from "./context/ChatContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

 
  return (
    <html lang="en">
      <body>
        <ChatContext >
        <div className="flex">
          <Sidebar />
          <div className=" w-[100%] ">
            <ChatHeader />
            {children}
          </div>
          <div>
            <Reply />
          </div>
        </div>
        </ChatContext>
      </body>
    </html>
  );
}
